"""
Stock Analyzer API — FastAPI wrapper around stock_analyzer.py

Exposes the same price + news + Gemini analysis logic as a web API instead
of a CLI tool. Good for learning how to serve an LLM-backed feature over
HTTP, which is how most real apps use something like this (a frontend or
another service calls the endpoint instead of running a script).

Setup:
    pip install -r requirements.txt
    export GEMINI_API_KEY="your-key-here"

Run the server:
    uvicorn api:app --reload

Then try it:
    http://127.0.0.1:8000/view/AAPL       <- readable HTML page with the chart actually rendered
    http://127.0.0.1:8000/analyze/AAPL    <- same data as raw JSON (chart as base64 text)
    http://127.0.0.1:8000/chart/AAPL      <- just the chart, as a raw PNG image
    http://127.0.0.1:8000/docs            <- interactive API docs, auto-generated by FastAPI
"""

import base64
import os

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import HTMLResponse, Response
from pydantic import BaseModel

from stock_analyzer import (
    get_price_history,
    summarize_price_history,
    fetch_news_summary,
    analyze_with_gemini,
    render_candlestick_png,
)

app = FastAPI(
    title="Stock Analyzer API",
    description="Fetches real stock data and news, then asks Gemini for a qualitative analysis. Not financial advice.",
    version="1.0.0",
)


class AnalysisResponse(BaseModel):
    ticker: str
    price_summary: str
    news_summary: str
    analysis: str
    chart_base64: str  # PNG image data, base64-encoded — see README for how to render it
    disclaimer: str = "This is a learning project, not financial advice."


@app.get("/")
def root():
    return {"message": "Stock Analyzer API. See /docs for usage, or GET /view/{ticker} for a readable page with the chart rendered."}


def _run_analysis(ticker: str, days: int):
    """Shared logic: fetch data, generate chart, call Gemini. Used by both
    the JSON endpoint (/analyze) and the HTML endpoint (/view)."""
    if not os.environ.get("GEMINI_API_KEY"):
        raise HTTPException(
            status_code=500,
            detail="GEMINI_API_KEY not set on the server. See README for setup.",
        )

    ticker = ticker.upper()

    try:
        hist = get_price_history(ticker, days)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))

    price_summary = summarize_price_history(hist, ticker, days)
    news_summary = fetch_news_summary(ticker)
    chart_bytes = render_candlestick_png(hist, ticker)
    chart_base64 = base64.b64encode(chart_bytes).decode("utf-8")

    try:
        analysis = analyze_with_gemini(price_summary, news_summary, ticker)
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Gemini request failed: {e}")

    return ticker, price_summary, news_summary, analysis, chart_base64


@app.get("/analyze/{ticker}", response_model=AnalysisResponse)
def analyze(ticker: str, days: int = Query(30, ge=5, le=365, description="Days of price history to analyze")):
    ticker, price_summary, news_summary, analysis, chart_base64 = _run_analysis(ticker, days)

    return AnalysisResponse(
        ticker=ticker,
        price_summary=price_summary,
        news_summary=news_summary,
        analysis=analysis,
        chart_base64=chart_base64,
    )


@app.get("/view/{ticker}", response_class=HTMLResponse)
def view(ticker: str, days: int = Query(30, ge=5, le=365, description="Days of price history to analyze")):
    """Same analysis as /analyze, but rendered as a readable HTML page
    (with the chart actually displayed as an image) instead of raw JSON."""
    ticker, price_summary, news_summary, analysis, chart_base64 = _run_analysis(ticker, days)

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>{ticker} Analysis</title>
        <style>
            body {{ font-family: -apple-system, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }}
            h1 {{ margin-bottom: 0.25rem; }}
            pre {{ white-space: pre-wrap; background: #f5f5f5; padding: 1rem; border-radius: 6px; }}
            img {{ max-width: 100%; border: 1px solid #ddd; border-radius: 6px; }}
            .disclaimer {{ color: #666; font-size: 0.9em; margin-top: 2rem; }}
        </style>
    </head>
    <body>
        <h1>{ticker}</h1>

        <h2>Price Chart</h2>
        <img src="data:image/png;base64,{chart_base64}" alt="{ticker} candlestick chart">

        <h2>Price Summary</h2>
        <pre>{price_summary}</pre>

        <h2>Recent Headlines</h2>
        <pre>{news_summary}</pre>

        <h2>Gemini Analysis</h2>
        <pre>{analysis}</pre>

        <p class="disclaimer">This is a learning project, not financial advice.</p>
    </body>
    </html>
    """
    return HTMLResponse(content=html)


@app.get("/chart/{ticker}")
def chart(ticker: str, days: int = Query(30, ge=5, le=365, description="Days of price history to chart")):
    """Returns a candlestick chart (PNG image) directly — open this URL in a browser to view it."""
    ticker = ticker.upper()

    try:
        hist = get_price_history(ticker, days)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))

    chart_bytes = render_candlestick_png(hist, ticker)
    return Response(content=chart_bytes, media_type="image/png")